[versions]
apolloRuntime = "4.0.0"
coilCompose = "2.7.0"
composeBom = "2024.12.01"
composeNavigation = "2.8.5"
composePreferences = "1.1.1"
converterMoshi = "2.11.0"
googleKsp = "2.1.0-1.0.29"
gradle = "8.7.3"
kotlin = "2.1.0"
kotlinxSerializationJson = "1.7.3"
lifecycleRuntimeKtx = "2.8.7"
material3 = "1.3.1"
moshiKotlin = "1.15.1"
okhttpBom = "4.12.0"
pagingCompose = "3.3.5"
retrofit = "2.11.0"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apolloRuntime" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlin" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
preference-library = { module = "me.zhanghai.compose.preference:library", version.ref = "composePreferences" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradle" }
apolloGraphQL = { id = "com.apollographql.apollo", version.ref = "apolloRuntime" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
googleKsp = { id = "com.google.devtools.ksp", version.ref = "googleKsp" }
jetbrainsKotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }