// Objective-C API for talking to yggbridge Go package.
//   gobind -lang=objc yggbridge
//
// File is generated by gobind. Do not edit.

#ifndef __Yggbridge_H__
#define __Yggbridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class YggbridgeResponse;

@interface YggbridgeResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long statusCode;
@property (nonatomic) NSString* _Nonnull headers;
@property (nonatomic) NSData* _Nullable body;
@end

FOUNDATION_EXPORT NSString* _Nonnull YggbridgeAddress(void);

FOUNDATION_EXPORT BOOL YggbridgeIsStarted(void);

FOUNDATION_EXPORT NSString* _Nonnull YggbridgePrivateKeyPEM(void);

/**
 * Request performs one complete buffered HTTP request.

headersJSON:

	{
	  "Authorization": ["Bearer ..."],
	  "Accept": ["application/json"]
	}

timeoutMillis:

60000 = 60 seconds
<= 0   = default timeout
 */
FOUNDATION_EXPORT YggbridgeResponse* _Nullable YggbridgeRequest(NSString* _Nullable method, NSString* _Nullable url, NSString* _Nullable headersJSON, NSData* _Nullable body, int64_t timeoutMillis, NSError* _Nullable* _Nullable error);

/**
 * Start receives peers as JSON:

["tls://peer1:443","quic://peer2:443"]

We use JSON because gomobile/gobind doesn't support []string
across the Java/Go boundary.
 */
FOUNDATION_EXPORT BOOL YggbridgeStart(NSString* _Nullable peersJSON, NSString* _Nullable savedPrivateKeyPEM, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL YggbridgeStop(NSError* _Nullable* _Nullable error);

#endif
