
// Objective-C API for talking to the following Go packages
//
//	yggbridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Yggbridge_FRAMEWORK_H__
#define __Yggbridge_FRAMEWORK_H__

#include "Yggbridge.objc.h"
#include "Universe.objc.h"

#endif
